---
title: "Mosaic_Catalog"
author: "brittth"
date: "13 May 2021"
output: word_document
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

# SETTINGS (Adjust them!)
```{r}
setwd('C:/Users/brittth/Documents/Mosaic_Catalog/')
```

# Install and load packages
```{r}
# install.packages('raster')
# install.packages('lubridate')
# install.packages("MODIS")
# install.packages('RStoolbox')
# install.packages('ggplot2')
# install.packages('grid')
# install.packages('gridExtra')
# install.packages('stringr')
# install.packages('rworldmap')
# install.packages('rworldxtra')
library(raster)
library(lubridate)
library(MODIS)
library(RStoolbox)
library(ggplot2)
library(grid)
library(gridExtra)
library(stringr)
library(rworldmap)
library(rworldxtra)
```

# Load data
```{r}
input <- read.csv('input/input.csv', sep=',')
```

# Create info table
```{r}
info.df <- data.frame('Mosaic File' = input$Mosaic.File.Name,
                      'Site' = input$Site,
                      'Sensor' = input$Mosaic.Sensor,
                      'Acquisition' = paste0(ymd(input$Mosaic.Acq.Date),', ',
                                             input$Mosaic.Acq.Time.Start,' - ',input$Mosaic.Acq.Time.Stop),
                      'Flight Lines' = input$No.Flight.Lines,
                      'Bands' = NA,
                      'Spatial Resolution' = NA,
                      'Area' = NA,
                      'File Size' = NA,
                      'File Format' = input$Mosaic.File.Format,
                      'File Creator' = input$Mosaic.Creator,
                      'File Path' = input$Mosaic.Path)
```

# Create mosaic catalog page
```{r}
for (i in 1:nrow(info.df)){
  # i=9 # for testing
  
  # subset to dataset
  info <- info.df[i,]
  
  # get full file path
  if(info$File.Format == 'gri + grd'){
    full.path <- paste0(info$File.Path,info$Mosaic.File,'.gri')
  }else{
    full.path <- paste0(info$File.Path,info$Mosaic.File,'.bsq')
    } #(info$File.Format == 'bsq + hdr')
  
  # load raster info
  im <- brick(full.path)
  if(info$File.Format == 'bsq + hdr'){NAvalue(im) <- 0} # declare NAs (with bsq files they are 0)
  im.df <- as.data.frame(im[[1]], na.rm=TRUE) # only for are calculation
  
  # # get coordinate info for input file conversion from UTM to lon lat
  # cat(as.character(info$Mosaic.File),'\n',
  #     as.character(crs(im)),'\n',
  #     (xmin(im)+(xmax(im)-xmin(im))),'\n',
  #     (ymin(im)+(ymax(im)-ymin(im))),'\n\n')

  # fill in missing information
  info$File.Size <- paste(round(fileSize(full.path, units = "GB"), digits = 3),'GB')
  info$Bands <- nbands(im)
  info$Spatial.Resolution <- paste(round(res(im)[1], digits = 1),'m')
  info$Area <- paste(round(nrow(im.df)*res(im)[1]^2/1000000,digits = 3),'km\u00B2')
  
  # adapt 'File.Path' for multiline text
  split <- str_split(info$File.Path, "/", 5)
  info$File.Path <- paste0(split[[1]][1],'/',split[[1]][2],'/',split[[1]][3],'/',split[[1]][4],'/\n',split[[1]][5])
  
  # get transposed raster info
  info <- t(info)
  info <- cbind(row.names(info),info)
  info[,1] <- chartr('.', ' ', info[,1])
  info
  
  # create info grob for arrangement
  info.table <- tableGrob(info,theme = ttheme_minimal(core = list(fg_params=list(hjust =0,x=0,fontsize=10,fontface=c(rep(c('bold'),12),rep(c('plain'),12))))),
                          cols=NULL,rows=NULL,widths=unit(c(0.9,4),c("null","null")))
  # plot(info.table)

  # create TCI
  TCI.plot <- ggRGB(im,r=input$Red.Band[i], g=input$Green.Band[i], b=input$Blue.Band[i],
                      stretch='hist', maxpixels = ncell(im))+ #stretch='hist'
    theme_void()+
    theme(plot.title = element_text(size=12, face='bold',hjust = 0.5))
  # TCI.plot
  
  # create map data frame
  map.df <- data.frame('long' = input$Longitude[i],'lat' = input$Latitude[i],
                       'Mosaic' = input$Mosaic.File.Name[i],'Site' = input$Site[i])
  
  # get the world map
  worldMap <- getMap(resolution='high')
  
  # geographic Europe subset (a bit larger to include fringe countries in map)
  europeMap <- worldMap[worldMap$LON > -15 & worldMap$LON < 20
                        & worldMap$LAT > 25 & worldMap$LAT < 60,]
  
  # get list of relevant countries
  countries.df <- data.frame(europeMap)
  countries <- countries.df$NAME
  
  # select only the index of relevant countries
  countries.i <- which(worldMap$NAME%in%countries)
  
  # extract longitude and latitude border's coordinates of relevant countries
  europeCoords <- lapply(countries.i, function(i){
    df <- data.frame(worldMap@polygons[[i]]@Polygons[[1]]@coords)
    df$region =as.character(worldMap$NAME[i])
    colnames(df) <- list('long', 'lat', 'region')
    return(df)
  })
  europeCoords <- do.call('rbind', europeCoords)
  
  # create overview map
  map <- ggplot() +
    geom_polygon(data = europeCoords, aes(x = long, y = lat, group = region),#, fill= region
                 colour = 'black', fill= 'white',size = 0.1, show.legend = FALSE) +
    geom_point(data = map.df, aes(x = long, y = lat),
               color = 'red', fill= 'red', size = 4, shape = 19) +
    coord_map(xlim = c(-10, 17),  ylim = c(35, 55))+
    labs(x = 'Longitude [°E]', y = 'Latitude [°N]')+
    theme(plot.title = element_text(hjust = 0.5, face = 'bold'),
          legend.title = element_text(face = 'bold'),
          axis.title = element_text(hjust = 0.5, face = 'plain'),
          panel.grid.major = element_line(colour = 'lightgrey'),
          panel.background = element_rect(fill = 'aliceblue', colour = 'black'))
  map
  
  # arrange overview map, TCI and info table
  lay <- rbind(c(1,2),
               c(3,3))
  map.TCI.info.plot <- grid.arrange(map,TCI.plot,info.table,nrow=2,ncol=2,
                                    layout_matrix = lay, widths=c(1,3), heights=c(3,2))
  
  # write to disc
  ggsave(file=paste0('output/',input$Mosaic.File.Name[i],'_map_TCI_info_plot.png'),
         plot=map.TCI.info.plot, width=10, height=10, dpi = 300)
  
}
```

```{r}
```